//! `defect-llm` 的 OAS → Rust 客户端 codegen 脚手架。
//!
//! 跑法：
//! ```bash
//! cargo run -p defect-llm-codegen -- anthropic   # 仅生成 Anthropic
//! cargo run -p defect-llm-codegen -- openai      # 仅生成 OpenAI
//! cargo run -p defect-llm-codegen --             # 两个一起
//! cargo run -p defect-llm-codegen -- --check     # CI 守门：重生不允许有 diff
//!
//! cargo run -p defect-llm-codegen -- openai-strip \
//!     --upstream ../tower-openapi-client/examples/openai-openapi/openapi.yaml
//! ```
//!
//! 这里**不**走 `toac_build::Builder::emit()`——它强制写 `$OUT_DIR`，
//! 期望被 `build.rs` 调。我们要把生成的代码 commit 进仓库，所以走底
//! 层 `toac_build::build_with` + 自己 `prettyplease::unparse` + 写文件。

mod anthropic_strip;
mod openai_strip;

use std::{
    env, fs,
    path::{Path, PathBuf},
    process::ExitCode,
};

use anyhow::{Context, Result, bail};
use toac_build::{BuildOptions, build_with};

const TARGETS: &[(&str, &str, &str, &str)] = &[
    // (name,        oas relative path,            output relative path,            root_path)
    (
        "anthropic",
        "crates/llm/oas/anthropic.yaml",
        "crates/llm/src/wire/anthropic.rs",
        "crate::wire::anthropic",
    ),
    (
        "openai",
        "crates/llm/oas/openai.yaml",
        "crates/llm/src/wire/openai.rs",
        "crate::wire::openai",
    ),
];

const HEADER: &str = "\
// @generated by defect-llm-codegen — do not edit by hand.
// Source OAS: ";

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(err) => {
            eprintln!("error: {err:#}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<()> {
    let args: Vec<String> = env::args().skip(1).collect();

    // `openai-strip` 是上游同步专用的 subcommand，走单独 pipeline——
    // 不读 oas/openai.yaml 而是 fork 上游 spec 到那里。
    if args.first().map(String::as_str) == Some("openai-strip") {
        return openai_strip::run(&args[1..]);
    }

    let workspace_root = workspace_root()?;
    let check = args.iter().any(|a| a == "--check");
    let names: Vec<&str> = args
        .iter()
        .filter(|a| !a.starts_with("--"))
        .map(String::as_str)
        .collect();

    let selected: Vec<_> = if names.is_empty() {
        TARGETS.to_vec()
    } else {
        let mut out = Vec::new();
        for n in &names {
            let Some(t) = TARGETS.iter().copied().find(|t| t.0 == *n) else {
                bail!(
                    "unknown target {n:?}; choices: {}",
                    TARGETS.iter().map(|t| t.0).collect::<Vec<_>>().join(", ")
                );
            };
            out.push(t);
        }
        out
    };

    for (name, oas_rel, out_rel, root_path) in selected {
        let oas_path = workspace_root.join(oas_rel);
        let out_path = workspace_root.join(out_rel);
        if !oas_path.exists() {
            eprintln!("[skip] {name}: {} not found", oas_path.display());
            continue;
        }
        let rendered = generate(name, &oas_path, root_path)?;

        if check {
            verify_in_place(&out_path, &rendered, name)?;
            println!("[ok]   {name}: {} matches", out_path.display());
        } else {
            ensure_parent(&out_path)?;
            fs::write(&out_path, &rendered)
                .with_context(|| format!("write {}", out_path.display()))?;
            println!("[gen]  {name}: {}", out_path.display());
        }
    }

    Ok(())
}

/// 生成单个 target 的完整 Rust 文件内容（含 header）。
fn generate(name: &str, oas_path: &Path, root_path: &str) -> Result<String> {
    let raw =
        fs::read_to_string(oas_path).with_context(|| format!("read {}", oas_path.display()))?;
    let spec = parse_spec(oas_path, &raw)?;
    let options = BuildOptions {
        root_path: syn::parse_str(root_path)
            .with_context(|| format!("parse root_path {root_path:?} for {name}"))?,
        ..BuildOptions::default()
    };
    let tokens =
        build_with(&spec, options).with_context(|| format!("toac_build::build_with({name})"))?;
    let parsed: syn::File =
        syn::parse_file(&tokens.to_string()).with_context(|| format!("syn::parse_file({name})"))?;
    let body = prettyplease::unparse(&parsed);
    // toac quirk patches per provider。`nullable: true` 在 OAS 里被 toac
    // 翻成 `Vec<T>` 而不是 `Option<Vec<T>>`，serde 默认遇到字段缺失就报错；
    // 单条 patch 的形态见各 strip 模块。
    let body = match name {
        "anthropic" => anthropic_strip::patch_generated(&body)
            .with_context(|| format!("anthropic_strip::patch_generated({name})"))?,
        _ => body,
    };
    let oas_rel = oas_path
        .strip_prefix(workspace_root()?)
        .map(Path::to_path_buf)
        .unwrap_or_else(|_| oas_path.to_path_buf());
    let mut out = String::with_capacity(body.len() + 256);
    out.push_str(HEADER);
    out.push_str(&oas_rel.display().to_string());
    out.push_str("\n// Re-run via `cargo run -p defect-llm-codegen -- ");
    out.push_str(name);
    out.push_str("`.\n#![allow(\n    clippy::manual_async_fn,\n    clippy::needless_return,\n    clippy::single_match,\n    clippy::match_single_binding,\n    clippy::too_many_arguments,\n    clippy::large_enum_variant,\n    clippy::enum_variant_names,\n    dead_code,\n    unused_imports,\n    rustdoc::bare_urls,\n    rustdoc::broken_intra_doc_links,\n)]\n\n");
    out.push_str(&body);
    Ok(out)
}

fn parse_spec(path: &Path, raw: &str) -> Result<oas3::Spec> {
    let ext = path
        .extension()
        .and_then(|s| s.to_str())
        .map(str::to_ascii_lowercase);
    match ext.as_deref() {
        Some("yaml" | "yml") => {
            oas3::from_yaml(raw).with_context(|| format!("parse YAML spec {}", path.display()))
        }
        Some("json") => {
            oas3::from_json(raw).with_context(|| format!("parse JSON spec {}", path.display()))
        }
        _ => bail!("unrecognised spec extension on {}", path.display()),
    }
}

fn verify_in_place(out_path: &Path, expected: &str, name: &str) -> Result<()> {
    let actual = fs::read_to_string(out_path)
        .with_context(|| format!("read {} for --check", out_path.display()))?;
    if actual == expected {
        Ok(())
    } else {
        bail!(
            "{name}: {} is stale — re-run `cargo run -p defect-llm-codegen -- {name}` and commit the result",
            out_path.display()
        )
    }
}

fn ensure_parent(p: &Path) -> Result<()> {
    if let Some(parent) = p.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("create_dir_all {}", parent.display()))?;
    }
    Ok(())
}

/// 推断 workspace 根：优先 `CARGO_WORKSPACE_DIR`（cargo 1.79+ 注入），
/// 否则从 `CARGO_MANIFEST_DIR` 上溯到含 `Cargo.toml` 且声明 `[workspace]`
/// 的目录。
pub(crate) fn workspace_root() -> Result<PathBuf> {
    if let Some(p) = env::var_os("CARGO_WORKSPACE_DIR") {
        return Ok(PathBuf::from(p));
    }
    let manifest = env::var_os("CARGO_MANIFEST_DIR")
        .context("CARGO_MANIFEST_DIR is unset (run via `cargo run`)")?;
    let mut cur = PathBuf::from(manifest);
    loop {
        let candidate = cur.join("Cargo.toml");
        if candidate.exists() {
            let txt = fs::read_to_string(&candidate)
                .with_context(|| format!("read {}", candidate.display()))?;
            if txt.contains("[workspace]") {
                return Ok(cur);
            }
        }
        if !cur.pop() {
            bail!("could not locate workspace root from CARGO_MANIFEST_DIR");
        }
    }
}
